# Generated by Django 5.0.3 on 2024-07-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Clinica Medica', 'Clinica Medica'), ('Pediatria', 'Pediatria'), ('Neurologia', 'Neurologia'), ('Cardiologia', 'Cardiologia'), ('Ginecologia', 'Ginecologia'), ('Ortopedia', 'Ortopedia')], max_length=255, null=True),
        ),
    ]
