# Generated by Django 5.0.3 on 2024-07-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_consultaagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaagenda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceite', 'Aceite'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
