# Generated by Django 5.0.3 on 2024-08-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_consultaagenda_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.PositiveIntegerField()),
                ('nacionalidade', models.CharField(max_length=120)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=50)),
                ('profissao', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('especialidade', models.CharField(choices=[('Ginecologia', 'Ginecologia'), ('Cirugia', 'Cirugia'), ('Dermatologia', 'Dermatologia'), ('Odontologia', 'Odontolgia'), ('Oftamologia', 'Oftamologia'), ('Nutricao', 'Nutricao')], max_length=120)),
                ('formacao', models.TextField()),
                ('foto', models.ImageField(upload_to='imagens_medico/')),
            ],
        ),
    ]
