# Generated by Django 5.0.3 on 2024-08-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_medicoespecialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_especialista',
            field=models.BooleanField(default=False, verbose_name='Is especialista'),
        ),
    ]
