# Generated by Django 5.0.3 on 2024-08-05 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_is_especialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaagenda',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
