# Generated by Django 5.0.3 on 2024-08-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_consultaagenda_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidade_agendamento',
            field=models.CharField(choices=[('Ginecologia', 'Ginecologia'), ('Cirugia', 'Cirugia'), ('Dermatologia', 'Dermatologia'), ('Odontologia', 'Odontolgia'), ('Oftamologia', 'Oftamologia'), ('Nutricao', 'Nutricao')], default=str, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='is_especialista',
            field=models.BooleanField(default=False, verbose_name='Is especialista'),
        ),
    ]
