# Generated by Django 5.0.3 on 2024-08-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_medico_especialidade_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('Clinica Medica', 'Clinica Medica'), ('Pediatria', 'Pediatria'), ('Neurologia', 'Neurologia'), ('Cardiologia', 'Cardiologia'), ('Ginecologia', 'Ginecologia'), ('Ortopedia', 'Ortopedia')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade_agendamento',
            field=models.CharField(blank=True, choices=[('Ginecologia', 'Ginecologia'), ('Cirugia', 'Cirugia'), ('Dermatologia', 'Dermatologia'), ('Odontologia', 'Odontolgia'), ('Oftamologia', 'Oftamologia'), ('Nutricao', 'Nutricao')], max_length=120, null=True),
        ),
    ]
