# Generated by Django 5.0.3 on 2024-08-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_medico_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaagenda',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
