# Generated by Django 5.0.3 on 2024-08-06 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_consultaagenda_medico_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaagenda',
            name='hora_pedido',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
