# Generated by Django 5.0.3 on 2024-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_consultaagenda_hora_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('Area_corporal_amostra', models.CharField(max_length=100)),
                ('Descricao', models.TextField()),
            ],
        ),
    ]
