# Generated by Django 5.0.3 on 2024-08-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_analise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.analise')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.receita')),
            ],
        ),
    ]
