# Generated by Django 5.0.3 on 2024-08-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_receitaanalise'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='preco',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
