# Generated by Django 5.0.3 on 2024-08-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_receita_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=20, null=True),
        ),
    ]
